BOW,TFIDF,Machine Learning Algorithms

- Preprocessing And Cleaning
- Train Test Split
- BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}
- Trained Our Models

In [66]:
import pandas as pd
messages=pd.read_csv('SpamClassifier-master/smsspamcollection/SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [67]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [68]:
## Data Cleaning And Preprocessing
# import re
# import nltk
# nltk.download('stopwords')

In [69]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [70]:
import re
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [71]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

Create Bag Of Words


In [72]:
## Output Features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [73]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [74]:
X_train

['hi darlin ive got back realli nice night thank much lift see u tomorrow xxx',
 'well meant oppos drunken night',
 'sorri call later',
 'sinc side fever vomitin',
 'remind hr',
 'ok',
 'believ true incred txt repli g learn truli amaz thing blow mind fwd p txt',
 'rememb ask alex pizza',
 'ye outsid like hour call whole famili wake caus start',
 'tb persolvo chase us sinc sept definit pay thank inform ignor kath manchest',
 'ever easier',
 'someon year lt gt toyota camri like mr olayiwola mileag lt gt k clean need know much sell rais dough soon land sell holla back',
 'wondar full flim',
 'haiyoh mayb hamster jealou million',
 'lyricalladi f invit friend repli ye see www sm ac u hmmross stop send stop frnd',
 'huh earli dinner outsid izzit',
 'sure get acknowledg astoundingli tactless gener faggi demand blood oath fo',
 'project pa come',
 'cd u congratul ur award cd gift voucher gift guarante freeentri wkli draw xt music tnc www ldew com win ppmx age',
 'hi happi new year dont mean in

In [75]:
y_train

array([ True,  True,  True,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ..., False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True])

In [76]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [77]:
len(X_train),len(y_train)

(4457, 4457)

In [78]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [79]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [80]:
cv.vocabulary_

{'hi': 927,
 'darlin': 479,
 'ive': 1040,
 'got': 839,
 'back': 137,
 'realli': 1700,
 'nice': 1427,
 'night': 1430,
 'thank': 2095,
 'much': 1383,
 'lift': 1155,
 'see': 1813,
 'tomorrow': 2156,
 'xxx': 2469,
 'hi darlin': 929,
 'got back': 840,
 'see tomorrow': 1816,
 'well': 2386,
 'meant': 1281,
 'sorri': 1939,
 'call': 244,
 'later': 1112,
 'sorri call': 1940,
 'call later': 256,
 'sinc': 1889,
 'side': 1880,
 'fever': 679,
 'remind': 1724,
 'hr': 975,
 'ok': 1473,
 'believ': 168,
 'true': 2189,
 'txt': 2205,
 'repli': 1732,
 'learn': 1130,
 'truli': 2191,
 'thing': 2104,
 'mind': 1309,
 'rememb': 1723,
 'ask': 105,
 'alex': 47,
 'pizza': 1574,
 'ye': 2476,
 'outsid': 1519,
 'like': 1159,
 'hour': 968,
 'whole': 2398,
 'famili': 658,
 'wake': 2330,
 'caus': 311,
 'start': 1973,
 'like hour': 1161,
 'tb': 2065,
 'chase': 329,
 'us': 2281,
 'sept': 1844,
 'definit': 507,
 'pay': 1538,
 'inform': 1018,
 'ignor': 997,
 'ever': 626,
 'someon': 1928,
 'year': 2485,
 'lt': 1220,
 'gt': 8

In [81]:
from sklearn.naive_bayes import MultinomialNB

In [82]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [83]:
y_pred=spam_detect_model.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score,classification_report

In [85]:
accuracy_score(y_test,y_pred)

0.979372197309417

In [86]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.94      0.91      0.93       160
        True       0.99      0.99      0.99       955

    accuracy                           0.98      1115
   macro avg       0.96      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



TF-IDF

In [87]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [89]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [90]:
tv.vocabulary_

{'want': 2330,
 'lick': 1141,
 'pussi': 1656,
 'wow': 2441,
 'boy': 213,
 'back': 143,
 'take': 2046,
 'uk': 2216,
 'tour': 2166,
 'win': 2398,
 'vip': 2301,
 'ticket': 2116,
 'book': 200,
 'club': 361,
 'txt': 2197,
 'ltd': 1219,
 'info': 1012,
 'dont': 566,
 'worri': 2433,
 'day': 496,
 'big': 174,
 'vl': 2304,
 'come': 385,
 'til': 2119,
 'enjoy': 622,
 'parti': 1526,
 'hey': 925,
 'realli': 1697,
 'pretti': 1635,
 'late': 1099,
 'go': 809,
 'lesson': 1134,
 'first': 710,
 'join': 1048,
 'reach': 1688,
 'mrt': 1358,
 'want go': 2333,
 'think': 2100,
 'one': 1487,
 'say': 1795,
 'ok': 1470,
 'leav': 1122,
 'need': 1399,
 'ask': 109,
 'end': 615,
 'might': 1291,
 'still': 1982,
 'vomit': 2307,
 'okay': 1481,
 'everyth': 651,
 'ye': 2473,
 'tv': 2194,
 'alway': 62,
 'avail': 126,
 'work': 2428,
 'place': 1579,
 'sorri': 1938,
 'call': 244,
 'later': 1100,
 'sorri call': 1939,
 'call later': 260,
 'dear': 509,
 'deni': 530,
 'word': 2425,
 'pleas': 1586,
 'lor': 1189,
 'buy': 235,
 'wat

In [91]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [92]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [93]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9829596412556054


In [94]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

       False       0.88      0.98      0.93       122
        True       1.00      0.98      0.99       993

    accuracy                           0.98      1115
   macro avg       0.94      0.98      0.96      1115
weighted avg       0.98      0.98      0.98      1115

