#### Word Embeddings

Feature Representation

Word2Vec -> Embedding Layer

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8930, 7119, 3865, 5020],
 [8930, 7119, 3865, 546],
 [8930, 1114, 3865, 4824],
 [6815, 4078, 2413, 6363, 4955],
 [6815, 4078, 2413, 6363, 2781],
 [6100, 8930, 7246, 3865, 3734],
 [3313, 2284, 6607, 6363]]

In [6]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
# Add padding to make all the sentence in same length
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8930 7119 3865 5020]
 [   0    0    0    0 8930 7119 3865  546]
 [   0    0    0    0 8930 1114 3865 4824]
 [   0    0    0 6815 4078 2413 6363 4955]
 [   0    0    0 6815 4078 2413 6363 2781]
 [   0    0    0 6100 8930 7246 3865 3734]
 [   0    0    0    0 3313 2284 6607 6363]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\GOPALAKRISHNAN\Downloads\python\AIML\machine_learning\0025_Deep_learning\0005_ANN_implementation\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.build((None, sent_length))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


array([[[ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [-0.04064248,  0.0477556 ,  0.042709  ,  0.03635826,
          0.00701703, -0.0145523 , -0.00617041, -0.03909545,
          0.02290014,  0.03936002],
        [ 0.02471845, -0.03008983, -0.04709941,  0.00158747,
         -0.01387819,  0.03255132, -0.00437915, -0.0443094 ,
         -0.0226428 ,  0.01362589],
        [-0.01707339,  0.04140595,  0.00878412, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8930, 7119, 3865, 5020])

In [17]:
# Reshape the input to include the batch dimension
single_sequence = np.expand_dims(embedded_docs[0], axis=0)


In [18]:
model.predict(single_sequence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[[ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [ 0.00202161,  0.01126107,  0.01771459,  0.00445823,
         -0.04891548,  0.00785565, -0.01859171, -0.0218289 ,
          0.00254079,  0.0293099 ],
        [-0.04064248,  0.0477556 ,  0.042709  ,  0.03635826,
          0.00701703, -0.0145523 , -0.00617041, -0.03909545,
          0.02290014,  0.03936002],
        [ 0.02471845, -0.03008983, -0.04709941,  0.00158747,
         -0.01387819,  0.03255132, -0.00437915, -0.0443094 ,
         -0.0226428 ,  0.01362589],
        [-0.01707339,  0.04140595,  0.00878412, -0.0